config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_companies
 
  namespace :admin do
      resources :users
      resources :companies

    root to: "users#index"
    end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # resources :companies
  # resources :users

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_company.rb
class AdminCompany < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  
end

app/models/company.rb
class Company < ApplicationRecord
    has_and_belongs_to_many :users
 
   
    validates :name, :location, :technology, presence: true 
    validates :name, :location, length: { minimum: 4, maximum: 50 }
     # validates :name, :location, :technology, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }


end

app/models/user.rb
class User < ApplicationRecord
    has_and_belongs_to_many :companies
   
    validates :name, :email_id, :phone_no, presence: true 
    validates :name, length: { minimum: 4, maximum: 50 }
    validates :email_id, confirmation: { case_sensitive: false }
        
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this
# `Administrate::ApplicationController`, making it the ideal place to put
# authentication logic or other before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin_company!

    # def authenticate_admin
    #   # TODO Add authentication logic here.
    # end
    


    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/companies_controller.rb
module Admin
  class CompaniesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
    
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def index

    #   #raise "test"

    # end
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
    def after_sign_in_path_for(resource)
        admin_companies_path
    end

    def after_sign_out_path_for(resource)
        admin_companies_path
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[show edit update destroy]
 

    def index
        @companies = Company.all
    end

    def new 
      @company =Company.new
    
    end

    def create
      @company =Company.new(companie_params)
      if @company.save
        redirect_to companies_path ,notice: "create successfully"
      else
        render
      end
    end

    def show
    end

    def edit
    end

    def update
       if @company.update(company_params)
           redirect_to @company, notice: "update successfully"
       else
           render :index
       end
    end
    def destroy
      @company.destroy
       redirect_to companies_path,notice: " delete successfully"
    end
 
   private
    def company_params
       params.require(:company).permit(:name, :location, :technology)
    end
 
    def set_company
       @company=Company.find(params[:id]) 
    end
      
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: %i[show edit update destroy]
    def index
        @users = User.all
    end
    def new
        @user =User.new
    end
    
    def create
        @user =User.new(user_params)
        if @user.save
          redirect_to users_path ,notice: "create successfully"
        else
          render 
        end
      end
  
      def show
      end
  
      def edit
      end
  
      def update 
        if @user.update(user_params)
            redirect_to @user, notice: "update successfully"
        else
            render :index
        end
     end
      
      def destroy
         @user.destroy
         redirect_to users_path, notice: " delete successfully"
      end
   
     private
      def user_params
         params.require(:user).permit(:name, :email_id, :phone_no)
      end
   
      def set_user
         @user=User.find(params[:id]) 
      end
        
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/empolyer_helper.rb
module EmpolyerHelper
end

app/views/admin/companies/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `collection_presenter`:
  An instance of [Administrate::Page::Collection][1].
  The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
  the columns displayed in the table
- `resources`:
  An ActiveModel::Relation collection of resources to be displayed in the table.
  By default, the number of resources is limited by pagination
  or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<table aria-labelledby="<%= table_title %>">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <th class="cell-label
        cell-label--<%= attr_type.html_class %>
        cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>
        cell-label--<%= "#{collection_presenter.resource_name}_#{attr_name}" %>"
        scope="col"
        role="columnheader"
        aria-sort="<%= sort_order(collection_presenter.ordered_html_class(attr_name)) %>">
        <%= link_to(sanitized_order_params(page, collection_field_name).merge(
          collection_presenter.order_params_for(attr_name, key: collection_field_name)
        )) do %>
        <%= t(
          "helpers.label.#{collection_presenter.resource_name}.#{attr_name}",
          default: resource_class.human_attribute_name(attr_name),
        ).titleize %>
            <% if collection_presenter.ordered_by?(attr_name) %>
              <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                <svg aria-hidden="true">
                  <use xlink:href="#icon-up-caret" />
                </svg>
              </span>
            <% end %>
          <% end %>
        </th>
      <% end %>
      <%= render(
        "collection_header_actions",
        collection_presenter: collection_presenter,
        page: page,
        resources: resources,
        table_title: "page-title"
      ) %>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <tr class="js-table-row"
          <% if accessible_action?(resource, :show) %>
            <%= %(tabindex=0 role=link data-url=#{polymorphic_path([namespace, resource])}) %>
          <% end %>
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <% if accessible_action?(resource, :show) -%>
              <a href="<%= polymorphic_path([namespace, resource]) -%>"
                 tabindex="-1"
                 class="action-show"
                 >
                <%= render_field attribute %>
              </a>
            <% else %>
              <%= render_field attribute %>
            <% end -%>
          </td>
        <% end %>

        <%= render(
          "collection_item_actions",
          collection_presenter: collection_presenter,
          collection_field_name: collection_field_name,
          page: page,
          namespace: namespace,
          resource: resource,
          table_title: "page-title"
        ) %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/companies/index.html.erb
<%#
# Index

This view is the template for the index page.
It is responsible for rendering the search bar, header and pagination.
It renders the `_table` partial to display details about the resources.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Collection][1].
  Contains helper methods to help display a table,
  and knows which attributes should be displayed in the resource's table.
- `resources`:
  An instance of `ActiveRecord::Relation` containing the resources
  that match the user's search criteria.
  By default, these resources are passed to the table partial to be displayed.
- `search_term`:
  A string containing the term the user has searched for, if any.
- `show_search_bar`:
  A boolean that determines if the search bar should be shown.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

   <% if  admin_company_signed_in?%>
       <%= link_to "signout", destroy_admin_company_session_path, method: :delete, class: "nav-link" %>
        <%else%>
       <%= link_to "signin", new_admin_company_session_path, class: "nav-link" %>
    <%end%>

<%=
  render("index_header",
    resources: resources,
    search_term: search_term,
    page: page,
    show_search_bar: show_search_bar,
  )
%>

<section class="main-content__body main-content__body--flush">
  <%= render(
    "collection",
    collection_presenter: page,
    collection_field_name: resource_name,
    page: page,
    resources: resources,
    table_title: "page-title"
  ) %>

  <%= render("pagination", resources: resources) %>
</section>

app/views/companies/_form.html.erb
<%= form_with model:@company do|form| %>
      <div>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
        <% @company.errors.full_messages_for(:name).each do |message| %>
            <div><%= message %></div>
          <% end %>
      </div>
  
      <div>
        <%= form.label :location %><br>
        <%= form.text_field :location %>
        <% @company.errors.full_messages_for(:location).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
  
      <div>
        <%= form.label :technology %><br>
        <%= form.text_field :technology %>
        <% @company.errors.full_messages_for(:technology).each do |message| %>
          <div><%= message %></div>
         <% end %>  
      </div>

      <div>
        <%= form.submit %>
      </div>
  <% end %>
  

app/views/companies/edit.html.erb
<h1> Edit company</h1>
   
<div>
<% companies.each do |company| %>
  <%= company.display_name %>
<% end %>
</div>

<%= render "form" %>
  

app/views/companies/index.html.erb
<p><%= notice %></p>

<h1>listing company </h1>
<%= link_to 'New Company', new_company_path %>
<table>
  <thead>
     <tr>
         <th>Company Name</th>
         <th>Location</th>
         <th>Technology</th>
         
         <th colspan="3">Actions</th>
     </tr>
   </thead>
   <tbody>
     <% @companies.each do |company| %>
      <tr>
        <td><%= company.name%></td>
        <td><%= company.location %></td>
        <td><%= company.technology %></td>

        <td><%= link_to 'View' , company %></td>
        <td><%= link_to 'Edit' , edit_company_path(company) %></td>
        <td><%= link_to "Destroy", company, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td> </tr> 
      <% end %>
    </tbody>
</table> 

app/views/companies/new.html.erb
<h1> new company</h1>

<%= render "form" %>
  

app/views/companies/show.html.erb
<p><%= notice %></p>

<h1> company detials</h1>
   <p><strong> Name:</strong><%= @company.name %></p> 
   <p><strong> location:</strong><%= @company.location %></p> 
   <p><strong> technology:</strong><%= @company.technology %></p> 

<%= link_to 'Back', companies_path %> | <%= link_to 'Edit' , edit_company_path(@company) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobBoard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with model:@user do|form| %>
      <div>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
        <% @user.errors.full_messages_for(:name).each do |message| %>
            <div><%= message %></div>
          <% end %>
      </div>
  
      <div>
        <%= form.label :email_id %><br>
        <%= form.text_field :email_id %>
        <% @user.errors.full_messages_for(:email_id).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
  
      <div>
        <%= form.label :phone_no %><br>
        <%= form.text_field :phone_no %>
        <% @user.errors.full_messages_for(:phone_no).each do |message| %>
          <div><%= message %></div>
         <% end %>  
      </div>

      <div>
        <%= form.submit %>
      </div>
  <% end %>
  

app/views/users/edit.html.erb
<h1> Edit User</h1>

<%= render "form" %>
  

app/views/users/index.html.erb
<p><%= notice %></p>

<h1>listing user </h1>
<%= link_to 'New user', new_user_path %>
<table>
  <thead>
     <tr>
         <th>Name</th>
         <th>Email id</th>
         <th>Phone no</th>
         
         <th colspan="3">Actions</th>
     </tr>
   </thead>
   <tbody>
     <% @users.each do |user| %>
      <tr>
        <td><%= user.name%></td>
        <td><%= user.email_id %></td>
        <td><%= user.phone_no %></td>

        <td><%= link_to 'View' , user %></td>
        <td><%= link_to 'Edit' , edit_user_path(user) %></td>
        <td><%= link_to "Destroy", user, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td> </tr> 
      <% end %>
    </tbody>
</table> 

app/views/users/new.html.erb
<h1> New User</h1>

<%= render "form" %>
  

app/views/users/show.html.erb
<p><%= notice %></p>

<h1> user detials</h1>
   <p><strong> Name:</strong><%= @user.name %></p> 
   <p><strong> Email ID:</strong><%= @user.email_id %></p> 
   <p><strong> Phone No:</strong><%= @user.phone_no %></p> 

<%= link_to 'Back', users_path %> | <%= link_to 'Edit' , edit_user_path(@user) %>